default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: dev_db

test:
  <<: *default
  database: test_db

production:
  <<: *default
  database: prod_db

